export interface Theme {
  id: "dark" | "light";
  tableBg: string;
  tableHeader: string;
  tableBorder: string;
  tableBorderSelected: string;
  columnText: string;
  columnType: string;
  headerText: string;
  pkBadge: string;
  fkBadge: string;
  uniqueBadge: string;
  nullBadge: string;
  edgeLine: string;
  edgeLineHover: string;
  canvasBg: string;
  enumBg: string;
  enumHeader: string;
  enumLabel: string;
  noteBg: string;
  noteBorder: string;
  noteTitle: string;
  noteText: string;
  groupBg: string;
  groupBorder: string;
  toolbarBg: string;
  toolbarBorder: string;
  toolbarText: string;
  toolbarTextMuted: string;
  toolbarAccent: string;
  toolbarSeparator: string;
  divider: string;
  dividerHover: string;
  dividerActive: string;
  editorBg: string;
  editorGutterBg: string;
  editorGutterText: string;
  editorCaret: string;
  editorSelection: string;
  editorActiveLine: string;
  editorMatchBracket: string;
  editorMatchBracketBorder: string;
  syntaxKeyword: string;
  syntaxString: string;
  syntaxNumber: string;
  syntaxComment: string;
  syntaxOperator: string;
  syntaxBracket: string;
  syntaxType: string;
  syntaxVariable: string;
  errorText: string;
  warningText: string;
  controlBg: string;
  controlBorder: string;
  controlText: string;
  controlHoverBg: string;
}

// "Graphite" — warm graphite board, plotter teal-cyan ink, red reserved as
// redline (errors only). A drafting instrument, not a cool-blue IDE.
export const darkTheme: Theme = {
  id: "dark",
  tableBg: "#202027",
  tableHeader: "#2b2b34",
  tableBorder: "#3a3a44",
  tableBorderSelected: "#46c7bd",
  columnText: "#d9d7cf",
  columnType: "#86847b",
  headerText: "#e8e6df",
  pkBadge: "#e0b072",
  fkBadge: "#46c7bd",
  uniqueBadge: "#93c17d",
  nullBadge: "#6b6a63",
  edgeLine: "#4a4a54",
  edgeLineHover: "#46c7bd",
  canvasBg: "#1b1b20",
  enumBg: "#202027",
  enumHeader: "#33333d",
  enumLabel: "#93c17d",
  noteBg: "#26251d",
  noteBorder: "#d98f5a",
  noteTitle: "#e0b072",
  noteText: "#d8d4c4",
  groupBg: "rgba(70, 199, 189, 0.06)",
  groupBorder: "#3a3a44",
  toolbarBg: "#111114",
  toolbarBorder: "#2a2a31",
  toolbarText: "#d9d7cf",
  toolbarTextMuted: "#86847b",
  toolbarAccent: "#46c7bd",
  toolbarSeparator: "#333139",
  divider: "#26262d",
  dividerHover: "#3a3a44",
  dividerActive: "#46c7bd",
  editorBg: "#151519",
  editorGutterBg: "#111114",
  editorGutterText: "#56554f",
  editorCaret: "#46c7bd",
  editorSelection: "#2b3a3a",
  editorActiveLine: "#1b1b20",
  editorMatchBracket: "#2f4a48",
  editorMatchBracketBorder: "#46c7bd",
  syntaxKeyword: "#d98f5a",
  syntaxString: "#93c17d",
  syntaxNumber: "#e0b072",
  syntaxComment: "#605f58",
  syntaxOperator: "#b0adc9",
  syntaxBracket: "#6b6a63",
  syntaxType: "#57c4bb",
  syntaxVariable: "#d9d7cf",
  errorText: "#ff6363",
  warningText: "#e6a95c",
  controlBg: "transparent",
  controlBorder: "#3a3a44",
  controlText: "#d9d7cf",
  controlHoverBg: "#2b2b34",
};

// "Vellum" — warm drafting paper, deep teal plotter ink. Light-mode twin of
// Graphite; red stays reserved as redline.
export const lightTheme: Theme = {
  id: "light",
  tableBg: "#f7f5ee",
  tableHeader: "#e6e3d7",
  tableBorder: "#cbc8bb",
  tableBorderSelected: "#1a8f86",
  columnText: "#45443c",
  columnType: "#8a887d",
  headerText: "#33322c",
  pkBadge: "#9a6a1a",
  fkBadge: "#1a8f86",
  uniqueBadge: "#4f7a3a",
  nullBadge: "#a3a196",
  edgeLine: "#b6b3a6",
  edgeLineHover: "#1a8f86",
  canvasBg: "#ecebe3",
  enumBg: "#f7f5ee",
  enumHeader: "#e6e3d7",
  enumLabel: "#4f7a3a",
  noteBg: "#f6efd2",
  noteBorder: "#b05a1e",
  noteTitle: "#9a6a1a",
  noteText: "#4a4840",
  groupBg: "rgba(26, 143, 134, 0.07)",
  groupBorder: "#cbc8bb",
  toolbarBg: "#e2e0d6",
  toolbarBorder: "#cfccbe",
  toolbarText: "#45443c",
  toolbarTextMuted: "#75736a",
  toolbarAccent: "#1a8f86",
  toolbarSeparator: "#cbc8bb",
  divider: "#d7d4c7",
  dividerHover: "#b6b3a6",
  dividerActive: "#1a8f86",
  editorBg: "#f4f2ea",
  editorGutterBg: "#e9e7dd",
  editorGutterText: "#a3a196",
  editorCaret: "#1a8f86",
  editorSelection: "#d3ded9",
  editorActiveLine: "#eceae1",
  editorMatchBracket: "#cfe0dc",
  editorMatchBracketBorder: "#1a8f86",
  syntaxKeyword: "#b05a1e",
  syntaxString: "#4f7a3a",
  syntaxNumber: "#9a6a1a",
  syntaxComment: "#9a988d",
  syntaxOperator: "#5a5788",
  syntaxBracket: "#8a8880",
  syntaxType: "#12857c",
  syntaxVariable: "#45443c",
  errorText: "#c8402f",
  warningText: "#b5791f",
  controlBg: "transparent",
  controlBorder: "#cbc8bb",
  controlText: "#45443c",
  controlHoverBg: "#e6e3d7",
};
