export interface Theme {
  id: "dark" | "light";
  tableBg: string;
  tableHeader: string;
  tableBorder: string;
  tableBorderSelected: string;
  columnText: string;
  columnType: string;
  headerText: string;
  pkBadge: string;
  fkBadge: string;
  uniqueBadge: string;
  nullBadge: string;
  edgeLine: string;
  edgeLineHover: string;
  canvasBg: string;
  enumBg: string;
  enumHeader: string;
  enumLabel: string;
  groupBg: string;
  groupBorder: string;
  toolbarBg: string;
  toolbarBorder: string;
  toolbarText: string;
  toolbarTextMuted: string;
  toolbarAccent: string;
  toolbarSeparator: string;
  divider: string;
  dividerHover: string;
  dividerActive: string;
  editorBg: string;
  editorGutterBg: string;
  editorGutterText: string;
  editorCaret: string;
  editorSelection: string;
  editorActiveLine: string;
  editorMatchBracket: string;
  editorMatchBracketBorder: string;
  syntaxKeyword: string;
  syntaxString: string;
  syntaxNumber: string;
  syntaxComment: string;
  syntaxOperator: string;
  syntaxBracket: string;
  syntaxType: string;
  syntaxVariable: string;
  errorText: string;
  warningText: string;
  controlBg: string;
  controlBorder: string;
  controlText: string;
  controlHoverBg: string;
}

export const darkTheme: Theme = {
  id: "dark",
  tableBg: "#1e1e2e",
  tableHeader: "#313244",
  tableBorder: "#45475a",
  tableBorderSelected: "#89b4fa",
  columnText: "#cdd6f4",
  columnType: "#6c7086",
  headerText: "#cdd6f4",
  pkBadge: "#f9e2af",
  fkBadge: "#89b4fa",
  uniqueBadge: "#a6e3a1",
  nullBadge: "#6c7086",
  edgeLine: "#585b70",
  edgeLineHover: "#89b4fa",
  canvasBg: "#11111b",
  enumBg: "#1e1e2e",
  enumHeader: "#45475a",
  enumLabel: "#a6e3a1",
  groupBg: "rgba(88, 91, 112, 0.1)",
  groupBorder: "#45475a",
  toolbarBg: "#181825",
  toolbarBorder: "#313244",
  toolbarText: "#cdd6f4",
  toolbarTextMuted: "#6c7086",
  toolbarAccent: "#89b4fa",
  toolbarSeparator: "#585b70",
  divider: "#313244",
  dividerHover: "#585b70",
  dividerActive: "#89b4fa",
  editorBg: "#1e1e2e",
  editorGutterBg: "#181825",
  editorGutterText: "#6c7086",
  editorCaret: "#f5e0dc",
  editorSelection: "#45475a",
  editorActiveLine: "#181825",
  editorMatchBracket: "#45475a",
  editorMatchBracketBorder: "#585b70",
  syntaxKeyword: "#cba6f7",
  syntaxString: "#a6e3a1",
  syntaxNumber: "#fab387",
  syntaxComment: "#6c7086",
  syntaxOperator: "#89b4fa",
  syntaxBracket: "#585b70",
  syntaxType: "#f9e2af",
  syntaxVariable: "#cdd6f4",
  errorText: "#f38ba8",
  warningText: "#f9e2af",
  controlBg: "transparent",
  controlBorder: "#45475a",
  controlText: "#cdd6f4",
  controlHoverBg: "#45475a",
};

export const lightTheme: Theme = {
  id: "light",
  tableBg: "#eff1f5",
  tableHeader: "#ccd0da",
  tableBorder: "#bcc0cc",
  tableBorderSelected: "#1e66f5",
  columnText: "#4c4f69",
  columnType: "#8c8fa1",
  headerText: "#4c4f69",
  pkBadge: "#df8e1d",
  fkBadge: "#1e66f5",
  uniqueBadge: "#40a02b",
  nullBadge: "#8c8fa1",
  edgeLine: "#9ca0b0",
  edgeLineHover: "#1e66f5",
  canvasBg: "#e6e9ef",
  enumBg: "#eff1f5",
  enumHeader: "#ccd0da",
  enumLabel: "#40a02b",
  groupBg: "rgba(156, 160, 176, 0.12)",
  groupBorder: "#bcc0cc",
  toolbarBg: "#dce0e8",
  toolbarBorder: "#ccd0da",
  toolbarText: "#4c4f69",
  toolbarTextMuted: "#8c8fa1",
  toolbarAccent: "#1e66f5",
  toolbarSeparator: "#bcc0cc",
  divider: "#ccd0da",
  dividerHover: "#9ca0b0",
  dividerActive: "#1e66f5",
  editorBg: "#eff1f5",
  editorGutterBg: "#e6e9ef",
  editorGutterText: "#8c8fa1",
  editorCaret: "#dc8a78",
  editorSelection: "#ccd0da",
  editorActiveLine: "#e6e9ef",
  editorMatchBracket: "#ccd0da",
  editorMatchBracketBorder: "#bcc0cc",
  syntaxKeyword: "#8839ef",
  syntaxString: "#40a02b",
  syntaxNumber: "#fe640b",
  syntaxComment: "#8c8fa1",
  syntaxOperator: "#1e66f5",
  syntaxBracket: "#9ca0b0",
  syntaxType: "#df8e1d",
  syntaxVariable: "#4c4f69",
  errorText: "#d20f39",
  warningText: "#df8e1d",
  controlBg: "transparent",
  controlBorder: "#bcc0cc",
  controlText: "#4c4f69",
  controlHoverBg: "#ccd0da",
};
